spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://devsquad.cgbzoy0x62zh.ap-northeast-2.rds.amazonaws.com:13306/DevSquad?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

