name: Java CI with Gradle

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 # JDK 설정, 점검
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Setup Gradle Wrapper
        run: gradle wrapper
      - name: Grant execute permission for gradlew # 실행 권한 부여
        run: chmod +x gradlew
      - name: Build with Gradle # ./gradlew 로 빌드
        run: ./gradlew build
      - name: Docker build # 도커로 이미지 생성 후 DockerHub에 배포
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t devsquad .
          docker tag devsquad ehdals0405/devsquad:${GITHUB_SHA::7}
          docker push ehdals0405/devsquad:${GITHUB_SHA::7}